### ISSUE TITLE
Distributor service incorrectly processes If-Modified-Since header

### ISSUE THREAD

**Issue by vpenyazkov** [51Degrees/documentation#14]
As stated in the docs, the endpoint `https://distributor.51degrees.com/api/v2/download` returns a `Last-Modified` headers with the date, which then can be passed into `If-Modified-Since` header to make request conditional and return 304 if the data has not been modified since.
The issue is that, if you pass value returned in `Last-Modified` header directly into `If-Modified-Since` header, the endpoint returns 200 always. It will return 304 only if you add at least a second to the former value. I looks wrong and the server should consider the value of `If-Modified-Since` inclusive.

Right now endpoint returns `Tue, 18 Jul 2023 13:46:24 GMT` in `Last-Modified` header, if you pass it directly into `If-Modified-Since` header and make request again -- 200 with file content is returned. If add one second to the value e.g. `Tue, 18 Jul 2023 13:46:25 GMT` and pass it -- 304 is returned as expected

**Comment by kirstin51D** [comment]
Thanks for raising this! We're currently upgrading our Distributor service, and we plan to address this issue as part of that. We expect the issue to be resolved in August.

**Comment by ben51degrees** [comment]
This is addressed in our latest set of changes to the Distributor service. We will close this issue once these changes are released.
